cart/urls.py
from django.conf.urls import url
from .import views

app_name = 'cart'

urlpatterns = [
    # r'^$' means empty string
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

loginapp/urls.py
from django.urls import path

from . import views


app_name = 'loginapp'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('signup', views.signup, name='signup'),
    path('password_reset', views.password_reset, name='password_reset'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('loginapp.urls', namespace='loginapp')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')), 
    url(r'^', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loginapp/models.py
from django.db import models

# Create your models here.

loginapp/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout

from .utils import random_string


def login(request):
    context = {}
    if request.method == 'POST':
        user = authenticate(request, 
            username=request.POST['user'], 
            password=request.POST['password'])
        if user:
            dj_login(request, user)
            # is this just stupid? context = {'user':request.POST['user']}
            return HttpResponseRedirect(reverse('shop:product_list'))
        else:
            #context = {'error':'Username or password is wrong.'}
            context['error'] = 'Username or password is wrong.'

    return render(request, 'loginapp/login.html', context)

def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('loginapp:login'))


def signup(request):
    if User.is_authenticated:
        dj_logout(request)
    context = {}
    if request.method == 'POST':
        if not request.POST['password'] == request.POST['repeatpassword']:
            context['error'] = 'Passwords do not match.'
            return render(request, 'loginapp/signup.html', context)
        if len(User.objects.filter(username=request.POST['user'])) > 0:
            context['error'] = 'Username already exists.'
            return render(request, 'loginapp/signup.html', context)
        user = User.objects.create_user(request.POST['user'],password=request.POST['password'])
        user.save()
        dj_login(request, user)
        return HttpResponseRedirect(reverse('shop:product_list'))

    return render(request, 'loginapp/signup.html')



def password_reset(request):
    context = {}
    if request.method == 'POST':
        users = User.objects.filter(username=request.POST['user'])
        if users:
            user = users[0]
            new_password = random_string()
            user.set_password(new_password)
            user.save()
            print(f'**** User {user} change password to {new_password}')
            return HttpResponseRedirect(reverse('loginapp:login'))
        else:
            context['error'] = 'No such username.'
        
    return render(request, 'loginapp/password_reset.html', context)

loginapp/templates/loginapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    {{user}}
    <form action="." method="POST">
        {% csrf_token %}
        <label for="user">Username</label>
        <br />
        <input type="text" id="user" name="user" placeholder="User Name">
        <br />
        <label for="password">Password</label>
        <br />
        <input type="password" id="password" name="password" placeholder="Password">
        <br />
        <input type="submit" value="Submit">
    </form>
    {% if error %}
        <p class="error">{{ error }}</p>
        <p><a href="{% url 'loginapp:password_reset' %}">Reset your password</a></p>
    {% endif  %}
    <hr>
    <a href="{% url 'loginapp:signup' %}">Sign up</a>
</body>
</html>

loginapp/templates/loginapp/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Password Reset</title>
</head>
<body>
    <h1>Password Reset</h1>
    {{user}}
    <form action="{% url 'loginapp:password_reset'  %}" method="POST">
        {% csrf_token %}
        <label for="user">Username</label>
        <br />
        <input type="text" id="user" name="user" placeholder="User Name">
        <br />
        <input type="submit" value="Submit">
    </form>
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif  %}
    <hr>
</body>
</html>

loginapp/templates/loginapp/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign-up</title>
</head>
<body>
    <h1>Sign-up</h1>
    <hr>
    <form action="{% url 'loginapp:signup' %}" method="POST">
            {% csrf_token %}
            <label for="user">Username</label>
            <br />
            <input type="text" id="user" name="user" placeholder="User Name">
            <br />
            <label for="password">Password</label>
            <br />
            <input type="password" id="password" name="password" placeholder="Password">
            <br />
            <label for="repeatpassword">Repeat Password</label>
            <br />
            <input type="password" id="repeatpassword" name="repeatpassword" placeholder="Repeat Password">
            <br />
            <input type="submit" value="Submit">
        </form>
    </body>
</html>